---
dist: bionic

services:
  - docker

before_install:
  - docker build -t packer .

script:
  - docker run --rm -v $(pwd):/yaml sdesbure/yamllint yamllint .
  - docker run --rm -v $(pwd):/usr/src/app packer validate vagrantbox.json
