---
dist: bionic
sudo: required

services:
  - docker

before_install:
  - docker build -t packer .

install:
  - sudo apt-get -y update
  - sudo apt-get -y install yamllint

script:
  - yamllint .
  - docker run --rm -v $(pwd):/usr/src/app packer validate vagrantbox.json
